// Generated by i18nline and preact-i18nline.
import I18n from 'preact-i18nline/i18n';

I18n.supportedLocales = ['en','fr','hi','ja','pl','pt','ru','sk'];
I18n.defaultLocale = 'en';

I18n.import = locale => {
	// we use a switch here so the import statements are statically
	// analyzable. the use of import() will make build tools generate
	// separate bundles which are downloaded on-demand.
	switch (locale) {
		case 'en': return import(/* webpackChunkName: 'i18n.en' */ './en.json');
		case 'fr': return import(/* webpackChunkName: 'i18n.fr' */ './fr.json');
		case 'hi': return import(/* webpackChunkName: 'i18n.hi' */ './hi.json');
		case 'ja': return import(/* webpackChunkName: 'i18n.ja' */ './ja.json');
		case 'pl': return import(/* webpackChunkName: 'i18n.pl' */ './pl.json');
		case 'pt': return import(/* webpackChunkName: 'i18n.pt' */ './pt.json');
		case 'ru': return import(/* webpackChunkName: 'i18n.ru' */ './ru.json');
		case 'sk': return import(/* webpackChunkName: 'i18n.sk' */ './sk.json');
		default: return import(/* webpackChunkName: 'i18n.default' */ './default.json');
	}
};

if ((typeof module === 'object') && module.hot) {
	module.hot.accept('./en.json', I18n.reload('en'));
	module.hot.accept('./fr.json', I18n.reload('fr'));
	module.hot.accept('./hi.json', I18n.reload('hi'));
	module.hot.accept('./ja.json', I18n.reload('ja'));
	module.hot.accept('./pl.json', I18n.reload('pl'));
	module.hot.accept('./pt.json', I18n.reload('pt'));
	module.hot.accept('./ru.json', I18n.reload('ru'));
	module.hot.accept('./sk.json', I18n.reload('sk'));
	module.hot.accept('./default.json', I18n.reload('default'));
}

export default I18n;
